INSERT INTO aluno (usuario, nome, matricula, senha) VALUES
  ('ana.clara', 'Ana Clara', '2023001', 'senha123'),
  ('bruno.lima', 'Bruno Lima', '2023002', 'senha123'),
  ('carla.mendes', 'Carla Mendes', '2023003', 'senha123'),
  ('daniel.souza', 'Daniel Souza', '2023004', 'senha123'),
  ('eduarda.silva', 'Eduarda Silva', '2023005', 'senha123'),
  ('felipe.ramos', 'Felipe Ramos', '2023006', 'senha123'),
  ('gabriela.rocha', 'Gabriela Rocha', '2023007', 'senha123'),
  ('henrique.alves', 'Henrique Alves', '2023008', 'senha123'),
  ('isabela.pinto', 'Isabela Pinto', '2023009', 'senha123'),
  ('joao.pedro', 'João Pedro', '2023010', 'senha123');


INSERT INTO livro (titulo, autor, codigo, disponivel) VALUES
  ('Introdução à Programação', 'Carlos Souza', 'LIV001', TRUE),
  ('Banco de Dados Avançado', 'Maria Tereza', 'LIV002', TRUE),
  ('Estruturas de Dados', 'João Silva', 'LIV003', TRUE),
  ('Algoritmos em Java', 'Ana Martins', 'LIV004', TRUE),
  ('Engenharia de Software', 'Ian Sommerville', 'LIV005', TRUE),
  ('Redes de Computadores', 'Andrew Tanenbaum', 'LIV006', TRUE),
  ('Sistemas Operacionais', 'Silberschatz', 'LIV007', TRUE),
  ('Cálculo I', 'James Stewart', 'LIV008', TRUE),
  ('Matemática Discreta', 'Kenneth Rosen', 'LIV009', TRUE),
  ('Lógica de Programação', 'Paulo Silveira', 'LIV010', TRUE),
  ('Python para Iniciantes', 'Luciano Ramalho', 'LIV011', TRUE),
  ('Programação em C', 'Dennis Ritchie', 'LIV012', TRUE),
  ('Fundamentos de Computação', 'Peter Norton', 'LIV013', TRUE),
  ('Desenvolvimento Web', 'Jon Duckett', 'LIV014', TRUE),
  ('HTML e CSS', 'Jon Duckett', 'LIV015', TRUE),
  ('JavaScript Moderno', 'Douglas Crockford', 'LIV016', TRUE),
  ('Java Avançado', 'Kathy Sierra', 'LIV017', TRUE),
  ('POO com Java', 'Deitel & Deitel', 'LIV018', TRUE),
  ('Banco de Dados com MySQL', 'Elmasri & Navathe', 'LIV019', TRUE),
  ('NoSQL Essencial', 'Pramod Sadalage', 'LIV020', TRUE),
  ('Docker para Desenvolvedores', 'Rafael Winterhalter', 'LIV021', TRUE),
  ('Git e GitHub', 'Scott Chacon', 'LIV022', TRUE),
  ('Clean Code', 'Robert C. Martin', 'LIV023', TRUE),
  ('Refatoração', 'Martin Fowler', 'LIV024', TRUE),
  ('Arquitetura de Software', 'Len Bass', 'LIV025', TRUE),
  ('DevOps na Prática', 'Gene Kim', 'LIV026', TRUE),
  ('Machine Learning', 'Tom Mitchell', 'LIV027', TRUE),
  ('Inteligência Artificial', 'Stuart Russell', 'LIV028', TRUE),
  ('Deep Learning', 'Ian Goodfellow', 'LIV029', TRUE),
  ('Segurança da Informação', 'William Stallings', 'LIV030', TRUE);
