services:
  postgres:
    image: postgres:15
    container_name: biblioteca-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblioteca-network  # Ajustando para o nome correto da rede
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: biblioteca-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - biblioteca-network  # Ajustando para o nome correto da rede
    restart: always

volumes:
  postgres_data:

networks:
  biblioteca-network:  # Ajustando para o nome correto da rede
    driver: bridge
